### PR TITLE
Update target frameworks

### PR DESCRIPTION
**Pull request by NeilSchiefer**
## Description

Updated target frameworks to support only net6.0, netcoreapp3.1, and net48.

Added .editorconfig and Directory.Build.props for consistency

## Type of change: 
This is a breaking change and will be updated version to 2.0.0.

---

<sup>_[Reviewer guidelines](../blob/main/CONTRIBUTING.md#reviewing-changes)_</sup>

### CODE REVIEW

**Review by JasonBock — APPROVED** [review]

**Comment by eslutz** [comment]
@NeilSchiefer @JasonBock I noticed this line in the .csproj file`<Copyright>Copyright 2017-2021 (c) Rocket Mortgage. All rights reserved.</Copyright>`.  Should we be updating the year on this as well?  Also, would it make more sense to move it to the Directory.Build.props file?  That way it's a centralized location making the Author and Copyright and easier to update/maintain and consistent between projects.

**Review by eslutz — APPROVED** [review]
Other than the question I had, everything looks good! 👍🏻

**Comment by JasonBock** [comment]
> @NeilSchiefer @JasonBock I noticed this line in the .csproj file`<Copyright>Copyright 2017-2021 (c) Rocket Mortgage. All rights reserved.</Copyright>`. Should we be updating the year on this as well? Also, would it make more sense to move it to the Directory.Build.props file? That way it's a centralized location making the Author and Copyright and easier to update/maintain and consistent between projects.

Yes, I agree. Feel free to update the baseline .props file and we can start to remove that from our projects going forward.

**Comment by NeilSchiefer** [comment]
> @NeilSchiefer @JasonBock I noticed this line in the .csproj file`<Copyright>Copyright 2017-2021 (c) Rocket Mortgage. All rights reserved.</Copyright>`. Should we be updating the year on this as well? Also, would it make more sense to move it to the Directory.Build.props file? That way it's a centralized location making the Author and Copyright and easier to update/maintain and consistent between projects.

Yeah I'm pretty sure I was thinking that I'd update when I update the version.  But yeah could be in the Directory.Build.props.  We can update that for this one when we do the last Configuration project though.

**Pull request merged**
