### PR TITLE
Added initial example configuration files

### PR DESCRIPTION
**Pull request by derikwhittaker**
Simple PR to start a list of example RockLib.config.json files

### CODE REVIEW

**Comment by bfriesen** [comment]
I'm not sure what the point of these config files is.

**Comment by derikwhittaker** [comment]
The point of them are to give users an a set of example files to be used as a starter file.  Same idea as the different .gitignore files you can get off of github.

**Comment by bfriesen** [comment]
I'm not sure these files provide enough value to exist. This package doesn't know anything about any specific settings - it's just the mechanism to access settings. As such, there aren't any useful examples that we could put here. RockLib doesn't have anything to do with connection strings, so adding an example is just noise. We wouldn't add encryption or messaging examples in this repository - examples would go in their respective repositories.

That said, if we do decide to keep these example configuration files, I have a few suggestions:
- Let's flesh this PR out (add some readme-style documentation, etc.) before merging.
- I'd prefer the `example config files` folder to not have spaces.
- I think the files should all be named the "standard" name of "rocklib.config.json". To differentiate, put them in different folders.

**Comment by peteraritchie** [comment]
Seems important to me to have examples. Is it that they exist as files as opposed to "documentation" @bfriesen? I have no problem with adding more detail and readme detail (and we should, I don't think this PR suggests this is the only documentation), but that doesn't mean it can't be another PR...

**Comment by mjeaton** [comment]
What do we want to do with this PR? @peteraritchie / @bfriesen / @derikwhittaker / @JustinMoss

**Comment by JustinMoss** [comment]
I think this is safe to close now that we have legit examples.

**Pull request closed without merging**
